<?php

declare(strict_types=1);

namespace App\ValueObjects;

final class Country
{
    public const VALID = [
        'AFG'      => 'Afghanistan',
        'ALB'      => 'Albania',
        'DZA'      => 'Algeria',
        'ASM'      => 'American Samoa',
        'AND'      => 'Andorra',
        'AGO'      => 'Angola',
        'AIA'      => 'Anguilla',
        'ATA'      => 'Antarctica',
        'ATG'      => 'Antigua and Barbuda',
        'ARG'      => 'Argentina',
        'ARM'      => 'Armenia',
        'ABW'      => 'Aruba',
        'AUS'      => 'Australia',
        'AUT'      => 'Austria',
        'AZA'      => 'Azerbaijan',
        'BHS'      => 'Bahamas',
        'BHR'      => 'Bahrain',
        'BGD'      => 'Bangladesh',
        'BRB'      => 'Barbados',
        'BLR'      => 'Belarus',
        'BEL'      => 'Belgium',
        'BLZ'      => 'Belize',
        'BEN'      => 'Benin',
        'BMU'      => 'Bermuda',
        'BTN'      => 'Bhutan',
        'BOL'      => 'Bolivia',
        'BIH'      => 'Bosnia and Herzegovina',
        'BWA'      => 'Botswana',
        'BVT'      => 'Bouvet Island',
        'BRA'      => 'Brazil',
        'IOT'      => 'British Indian Ocean Territory',
        'VGB'      => 'British Virgin Islands',
        'BRN'      => 'Brunei Darussalam',
        'BGR'      => 'Bulgaria',
        'BFA'      => 'Burkina Faso',
        'BDI'      => 'Burundi',
        'KHM'      => 'Cambodia',
        'CMR'      => 'Cameroon',
        'CAN'      => 'Canada',
        'CCPV'     => 'Cape Verde',
        'CYM'      => 'Cayman Islands',
        'CAF'      => 'Central African Republic',
        'TCD'      => 'Chad',
        'CHL'      => 'Chile',
        'CHN'      => 'China',
        'CXR'      => 'Christmas Island',
        'CCK'      => 'Cocos (Keeling) Islands',
        'COL'      => 'Colombia',
        'COM'      => 'Comoros',
        'COD'      => 'Congo',
        'COK'      => 'Cook Islands',
        'CRI'      => 'Costa Rica',
        'CIV'      => 'Côte d\'Ivoire',
        'HRV'      => 'Croatia',
        'UA-43'    => 'Crimea',
        'CUB'      => 'Cuba',
        'CUW'      => 'Curacao',
        'CYP'      => 'Cyprus',
        'CZE'      => 'Czech Republic',
        'DNK'      => 'Denmark',
        'DJI'      => 'Djibouti',
        'DMA'      => 'Dominica',
        'DOM'      => 'Dominican Republic',
        'ECU'      => 'Ecuador',
        'EGY'      => 'Egypt',
        'SLV'      => 'El Salvador',
        'GNQ'      => 'Equatorial Guinea',
        'ERI'      => 'Eritrea',
        'EST'      => 'Estonia',
        'ETH'      => 'Ethiopia',
        'GB-ENG'   => 'England',
        'SWZ'      => 'Eswatini',
        'FRO'      => 'Faroe Islands',
        'FLK'      => 'Falkland Islands (Malvinas)',
        'FJI'      => 'Fiji',
        'FIN'      => 'Finland',
        'FRA'      => 'France',
        'GUF'      => 'French Guiana',
        'PYF'      => 'French Polynesia',
        'ATF'      => 'French Southern Territories',
        'GAB'      => 'Gabon',
        'GMB'      => 'Gambia',
        'GEO'      => 'Georgia',
        'DEU'      => 'Germany',
        'GHA'      => 'Ghana',
        'GIB'      => 'Gibraltar',
        'GRC'      => 'Greece',
        'GRL'      => 'Greenland',
        'GRD'      => 'Grenada',
        'GLP'      => 'Guadeloupe',
        'GUM'      => 'Guam',
        'GTM'      => 'Guatemala',
        'GGY'      => 'Guernsey',
        'GIN'      => 'Guinea',
        'GNB'      => 'Guinea-Bissau',
        'GUY'      => 'Guyana',
        'HTI'      => 'Haiti',
        'HMD'      => 'Heard Island and McDonald Islands',
        'VAT'      => 'Holy See (Vatican City State)',
        'HND'      => 'Honduras',
        'HKG'      => 'Hong Kong',
        'HUN'      => 'Hungary',
        'ISL'      => 'Iceland',
        'IND'      => 'India',
        'IDN'      => 'Indonesia',
        'IRN'      => 'Iran',
        'IRQ'      => 'Iraq',
        'IRL'      => 'Ireland',
        'IMN'      => 'Isle of Man',
        'ISR'      => 'Israel',
        'ITA'      => 'Italy',
        'JAM'      => 'Jamaica',
        'JPN'      => 'Japan',
        'JEY'      => 'Jersey',
        'JOR'      => 'Jordan',
        'KAZ'      => 'Kazakhstan',
        'KEN'      => 'Kenya',
        'KIR'      => 'Kiribati',
        'KOR'      => 'South Korea',
        'RS-KM'    => 'Kosovo',
        'KWT'      => 'Kuwait',
        'KGZ'      => 'Kyrgyz',
        'LAO'      => 'Laos',
        'LVA'      => 'Latvia',
        'LBN'      => 'Lebanon',
        'LSO'      => 'Lesotho',
        'LBR'      => 'Liberia',
        'LBY'      => 'Libya',
        'LIE'      => 'Liechtenstein',
        'LTU'      => 'Lithuania',
        'LUX'      => 'Luxembourg',
        'MAC'      => 'Macao',
        'MKD'      => 'Macedonia',
        'MDG'      => 'Madagascar',
        'MWI'      => 'Malawi',
        'MYS'      => 'Malaysia',
        'MDV'      => 'Maldives',
        'MLI'      => 'Mali',
        'MLT'      => 'Malta',
        'MHL'      => 'Marshall Islands',
        'MTQ'      => 'Martinique',
        'MRT'      => 'Mauritania',
        'MUS'      => 'Mauritius',
        'MYT'      => 'Mayotte',
        'MEX'      => 'Mexico',
        'FSM'      => 'Micronesia',
        'MDA'      => 'Moldova',
        'MCO'      => 'Monaco',
        'MNG'      => 'Mongolia',
        'MNE'      => 'Montenegro',
        'MSR'      => 'Montserrat',
        'MAR'      => 'Morocco',
        'MOZ'      => 'Mozambique',
        'MNR'      => 'Myanmar',
        'NAM'      => 'Namibia',
        'NRU'      => 'Nauru',
        'NPL'      => 'Nepal',
        'ANT'      => 'Netherlands Antilles',
        'NLD'      => 'Netherlands',
        'NCL'      => 'New Caledonia',
        'NZL'      => 'New Zealand',
        'NIC'      => 'Nicaragua',
        'NER'      => 'Niger',
        'NGR'      => 'Nigeria',
        'NIU'      => 'Niue',
        'NFK'      => 'Norfolk Island',
        'MNP'      => 'Northern Mariana Islands',
        'GB-NIR'   => 'Northern Ireland',
        'PRK'      => 'North Korea',
        'NOR'      => 'Norway',
        'OMN'      => 'Oman',
        'PAK'      => 'Pakistan',
        'PLW'      => 'Palau',
        'PSE'      => 'Palestine',
        'PAN'      => 'Panama',
        'PNG'      => 'Papua New Guinea',
        'PRY'      => 'Paraguay',
        'PER'      => 'Peru',
        'PHL'      => 'Philippines',
        'PCN'      => 'Pitcairn Islands',
        'POL'      => 'Poland',
        'PRT'      => 'Portugal',
        'PRI'      => 'Puerto Rico',
        'QAT'      => 'Qatar',
        'REU'      => 'Reunion',
        'ROU'      => 'Romania',
        'RUS'      => 'Russia',
        'RWA'      => 'Rwanda',
        'BLM'      => 'Saint Barthelemy',
        'SHN'      => 'Saint Helena',
        'KNA'      => 'Saint Kitts and Nevis',
        'LCA'      => 'Saint Lucia',
        'MAF'      => 'Saint Martin',
        'SPM'      => 'Saint Pierre and Miquelon',
        'VCT'      => 'Saint Vincent and the Grenadines',
        'WSM'      => 'Samoa',
        'SMR'      => 'San Marino',
        'STP'      => 'Sao Tome and Principe',
        'SAU'      => 'Saudi Arabia',
        'GB-SCT'   => 'Scotland',
        'SEN'      => 'Senegal',
        'SRB'      => 'Serbia',
        'SYC'      => 'Seychelles',
        'SLE'      => 'Sierra Leone',
        'SGP'      => 'Singapore',
        'SVK'      => 'Slovakia',
        'SVN'      => 'Slovenia',
        'SLB'      => 'Solomon Islands',
        'SOM'      => 'Somalia',
        'ZAF'      => 'South Africa',
        'SGS'      => 'South Georgia and the South Sandwich Islands',
        'ESP'      => 'Spain',
        'LKA'      => 'Sri Lanka',
        'SDN'      => 'Sudan',
        'SUR'      => 'Suriname',
        'SJM'      => 'Svalbard & Jan Mayen Islands',
        'SWE'      => 'Sweden',
        'CHE'      => 'Switzerland',
        'SYR'      => 'Syria',
        'TWN'      => 'Taiwan',
        'TJK'      => 'Tajikistan',
        'TZA'      => 'Tanzania',
        'THA'      => 'Thailand',
        'TLS'      => 'Timor-Leste',
        'TGO'      => 'Togo',
        'TKL'      => 'Tokelau',
        'TON'      => 'Tonga',
        'TTO'      => 'Trinidad And Tobago',
        'TUN'      => 'Tunisia',
        'TUR'      => 'Turkey',
        'TKM'      => 'Turkmenistan',
        'TCA'      => 'Turks and Caicos Islands',
        'TUV'      => 'Tuvalu',
        'UGA'      => 'Uganda',
        'UKR'      => 'Ukraine',
        'ARE'      => 'United Arab Emirates',
        'GBR'      => 'United Kingdom',
        'USA'      => 'United States of America',
        'UMI'      => 'United States Minor Outlying Islands',
        'US-VI'    => 'United States Virgin Islands',
        'URY'      => 'Uruguay',
        'UZB'      => 'Uzbekistan',
        'VUT'      => 'Vanuatu',
        'VEN'      => 'Venezuela',
        'VNM'      => 'Vietnam',
        'WLF'      => 'Wallis and Futuna',
        'GB-WLS'   => 'Wales',
        'ESH'      => 'Western Sahara',
        'YEM'      => 'Yemen',
        'ZMB'      => 'Zambia',
        'ZWE'      => 'Zimbabwe',

        'World'    => 'World'
    ];

    /**
     * @var array<string>
     */
    private static array $checked = [];

    public function __construct(private string $name)
    {
        $this->validate();
    }

    private function validate(): void
    {
        if (inArray($this->name, self::$checked)) {
            return;
        }

        if (notInArray($this->name, self::VALID)) {
            throw new \InvalidArgumentException(
                'Invalid country name ' . $this->name
            );
        }

        self::$checked[] = $this->name;
    }

    public function name(): string
    {
        return $this->name;
    }
}
